vich_uploader:
    db_driver: orm

    mappings:
        order_document:
            uri_prefix: /uploads/documents
            upload_destination: '%kernel.project_dir%/public/uploads/documents'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            delete_on_update: true
            delete_on_remove: true
        dish_image:  
            uri_prefix: /uploads/dishes
            upload_destination: '%kernel.project_dir%/public/uploads/dishes'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            delete_on_update: true
            delete_on_remove: true